### PR TITLE
Explain how to use panels

### PR DESCRIPTION
**Pull request by modernben**

### CODE REVIEW

**Comment by Tarpsvo** [comment]
Heya! Thanks for the PR. Using Panels in NovaSettings is no different from using Panels in any Resource. Do you think it should be documented anyway? :) I thought it'd be obvious and I'd like to keep the documentation as short as possible.

**Comment by modernben** [comment]
Hey there @Tarpsvo I think it may be obvious to those who have used them in Nova core before but not maybe to those who are new/newer to Nova. I spent probably 2 hours trying to figure out how you did it. I dove your source and everything and could not figure it out. I finally found a StackOverflow on how to do it and figured it would be nice to add to the docs.

**Comment by Tarpsvo** [comment]
Alright, thanks! I added it just in case. :) Thank you!

**Comment by modernben** [comment]
Awesome! Thank you!

**Pull request merged**
