### PR TITLE
Using getValueForKey method instead of find in getSetting.

### PR DESCRIPTION
**Pull request by phuclh**
By using `getValueForKey` method from the `getSetting`, it can be flexible to add a cache layer in the custom Setting Model by overriding `getValueForKey` method like this:

```
// CustomSettingModel.php

public static function getValueForKey($key)
{
    return Cache::rememberForever(self::getCacheKey($key), function () use ($key) {
        $setting = static::where('key', $key)->get()->first();

        return isset($setting) ? $setting->value : null;
    });
}
```

### CODE REVIEW

**Review by Tarpsvo — APPROVED** [review]

**Comment by Tarpsvo** [comment]
Thanks, that does make sense. :)

**Comment by bluec** [comment]
Thanks for this. Any clues about how to invalidate the cache when a setting is saved?

**Comment by bluec** [comment]
Answering my own question... I guess this would do it:

```php
// CustomSettingModel.php

protected static function booted()
{
    static::updated(function ($setting) {
        Cache::forget(self::getCacheKey($setting->key));
    });
}
```

**Comment by Tarpsvo** [comment]
Heya! I added automatic memory cache clearing in version 4.0.4.

**Comment by bluec** [comment]
Hey @Tarpsvo thanks for this. I must admit I don't really understand the change and I wonder if we both have different meanings of "cache" in this context.

The shipped `NovaSettingsStore` class doesn't implement a true cache from what I can see. It only caches the settings within the currently instantiated object. So adding this on the `booted()` method of the model seems a bit confused and maybe also redundant. Every time the `NovaSettingsStore` class is instantiated it already has no cached values and when a setting is saved it already [removes that setting from the cache](https://github.com/outl1ne/nova-settings/blob/ae56298a2bb0dbcdb4a4add3592e195c5daa9351/src/NovaSettingsStore.php#L100).

This PR was about being able to use one of the Laravel [cache backends](https://laravel.com/docs/9.x/cache) for caching the settings values and reducing DB calls across multiple requests. The [changes in this commit](https://github.com/outl1ne/nova-settings/commit/ae56298a2bb0dbcdb4a4add3592e195c5daa9351) don't really solve this problem and actually seem quite confusing.

**Comment by Tarpsvo** [comment]
Yeah, it's an in-memory cache to avoid querying the database every time a value is requested during the same request. Ie if the user has multiple `nova_get_setting('test')` calls. This is just to help the user avoid duplicate SQL queries within the same request.

If you wish to cache the values into Redis or any other key-value store, you can create a new helper function (ie nova_get_cached_setting()) and put your abstract cache layer in there.

**Comment by bluec** [comment]
Ok yes, so this means that the change in 4.0.4 to clean the cache using the `booted()` method on the Setting model doesn't make sense and doesn't actually do anything.

**Comment by Tarpsvo** [comment]
The observer clears the in-memory cache in case a setting is saved in-between nova_get_setting() calls. It both makes sense and actually does what it's supposed to. This package only offers in-memory caching out of the box.

If you want to cache your settings in a different cache layer (ie Redis), you have to overwrite the Settings model and the getValueForKey function just like in the original post. You also have to register an observer to clear the cache, either in an observer class or in the static::booted() function.

**Comment by bluec** [comment]
Ah I had assumed every call to `nova_get_setting()` instantiated a new `NovaSettingsStore()` object but I hadn't spotted that this class is registered in the service container as a singleton so this makes sense. 

However, I still maintain that the observer is redundant since the [in-memory cache is already cleared when a setting is saved](https://github.com/outl1ne/nova-settings/blob/86ede484b9269b206bb83cf81ef77285cdd5a5c1/src/NovaSettingsStore.php#L100) and this would already clear the in-memory cache in case a setting is saved in-between nova_get_setting() calls.

(I understand about using a cache layer for more persistent cacheing which is what this PR was originally about.)

**Pull request merged**
