### PR TITLE
Laravel Translatable support

### PR DESCRIPTION
**Pull request by royduin**
Added support for Laravel Translatable from Spatie: https://github.com/spatie/laravel-translatable, in my case I'm using this Nova integration: https://github.com/mrmonat/nova-translatable. An example to get this working:

```
\OptimistDigital\NovaSettings\NovaSettings::setSettingsFields([
    Translatable::make('Name'),
    Translatable::make('Description'),
], function ($key, $value) {
    return in_array($key, ['name', 'description']) ? json_decode($value) : $value;
});
```

Fixes: https://github.com/optimistdigital/nova-settings/issues/5

### CODE REVIEW

**Comment by royduin** [comment]
Please merge and tag a new version.

**Comment by Tarpsvo** [comment]
Hey! Sorry for the delay, I was busy and totally forgot. I merged it and released it in version 2.3.0.

A  huge thank you for the contribution!

**Comment by royduin** [comment]
Great! Thanks 😎

**Comment by Tarpsvo** [comment]
Unfortunately, I had to undo the Translatable support in version 1.5.0 as it introduced too many breaking changes. Not being able to add an array as a setting's value without it getting encoded to a string doesn't seem like expected behaviour.

Isn't there any other way to provide support for Translatable?

**Comment by royduin** [comment]
I don't see the issue, do you have an example where this is breaking? When the value is an array you'll get an error about the array to string conversion...

**Comment by Tarpsvo** [comment]
You're right, I fucked up. Encoding is the correct way to go in this case, though I was using the `value` attribute for storing PHP arrays. I'll just refactor it and use `json_decode` for the value when required. Undid the release. 🤕

**Comment by royduin** [comment]
1.5.0 is still in Packagist @Tarpsvo.

**Comment by Tarpsvo** [comment]
Ah yeah, damn. Removed it now. Thanks!

**Pull request merged**
